spring.application.name=hangman-backend

# Server
server.port=8080

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/hangmandb
spring.datasource.username=root
spring.datasource.password=Aman@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

gemini.api.key=AIzaSyAR6QVPf8k9pRNYSCDZ6kn6S0YgXSoTnk0

# CORS (we?ll allow React on port 5173)
# Optional: if doing manual config
e
